apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ef9fcf5pc-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ef9fcf5pc-java-quarkus-gitops